[DBZ-PGYB] Non-key columns should always be optional for replica identity CHANGE (#147)
## Problem

Suppose we create a table which has a non-key column which also has a
constraint `NOT NULL` - when the connector will start and CDC service
will send a `RELATION` message, the column will be marked as "required"
since a `NOT NULL` column means that the value should be present.

But for a table with replica identity `CHANGE` the column will not be
present in `UPDATE` operations if the column is not updated. This will
violate the assumption of the column being marked as "required" since
the value will not be present and the connector will end up throwing
error of a similar format as:

```
org.apache.kafka.connect.errors.DataException: Invalid value: null used for required field: "name", schema type: STRUCT
```

## Solution

This PR introduces a fix to the above problem by adding a check while
decoding the relation message - the check essentially verifies that if
the replica identity of the table is `CHANGE` then we explicitly mark
the column as optional **if it is a non key column**.